#!/bin/sh

if [ -z "$GISBASE" ] ; then
    echo "You must be in GRASS GIS to run this program." 1>&2
    exit 1
fi


eval $(g.gisenv)

db.connect driver=sqlite database=$GISDBASE/$LOCATION_NAME/$MAPSET/$MAPSET.db


g.mlist vect | while read VECT; do
    IF_TABLE=$(v.db.connect -g ${VECT})
    if [ -n "$IF_TABLE" ]; then
	db.copy from_driver=dbf \
	    from_database=${GISDBASE}/${LOCATION_NAME}/${MAPSET}/dbf \
	    from_table=${VECT} to_driver=sqlite \
	    to_database=${GISDBASE}/${LOCATION_NAME}/${MAPSET}/${MAPSET}.db \
	    to_table=${VECT}
	
	
	v.db.connect -o map=${VECT} driver=sqlite \
	    database=${GISDBASE}/${LOCATION_NAME}/${MAPSET}/${MAPSET}.db \
	    table=${VECT}
	
    fi

done




